user.account: ds6011-sp22-002
run.workdir: /project/ds6011-sp22-002/runner/mlcommons
run.resourcedir: /project/ds6011-sp22-002
run.datadir: data
run.branch: features/63-sbatch-mods
system.python: 3.10.2
system.num_cpus: 6
system.partition: gpu
time: 3-0
set_soft_device_placement: false
debugging_set_log_device_placement: false
DLAnalysisOnly: false
DLRestorefromcheckpoint: false
DLinputCheckpointpostfix: ''
TFTTransformerbatch_size: 64
TFTd_model: 160
Tseq: 26
TFTdropout_rate: 0.1
learning_rate: 5.0e-07
max_gradient_norm: 0.01
early_stopping_patience: 60
TFTnum_AttentionLayers: 2
TFTnum_heads: 4
meta.parent.uuid: run
cloudmesh.timer: 'False'
card_name: v100
gpu_count: '1'
cpu_num: '6'
mem: 64GB
TFTTransformerepochs: '2'
meta.uuid: manual
